language: java
jdk: openjdk8
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: TaWXrg5y0wS2WBguaI9x8a/Wk0l6wKsAYfcsrUM+uly6Eh60p2n3EH2/n+fZAmKJFpg9t745H2yFJHVKIVuKQY1khPhaxx8apcnsWnP0CQSpFC6zc7ciSgE8mT2whY4EsFX7izHYzcbHF3iuZ3DuKY/wxp+ToYL8oMS7jwZhaxrGl1857J9JW9dFogmGvOsq4aYY0lezSCjxB/ZuHuISXTo2xZww/0iFr1pXWrL0seG9T7jeXv2tJK1V2oQaho7dpSrB8kH6qiBibSH4ieKu9vLugr4UaP3ej7ldPWEozbi63TAR8bf9BHRHcmlcasvyDugGgIi8qkCBg7oVtaCpmafCNgdscttZLED2jt34gsWGwx614vNf4Xgusbb6uCFb+jXLD+1ymVzC6yUvj/RhOaV26YvLFpdgNDU3+l5sok4etQO14UGgNt7Mxieklmw0RquDf7wzUbs5jA3kUgxkeJPhbVFf0tgupzONAt8N6mGVxSpOYaJuFNH8CMVsT0rUlmP1c7CTa+KVAiLTkjVayWGoxNdeJGJ3FO/BLH3vlR5E/o131L9VTLeQpHywuP7UFkcM+34vaczjSd7ZtVCTzgm0jAt3Mz/LpMYrNpcAqstOYKjYUlfioO4EmsssZrWVCA+7b9JIhvYZO9YYOTN5+eFLxpk+sKIVZwHXGgz+8Ik=
  file:
      - target/ebms-core-${project.version}.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-core
  name: ${project.version}

